language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t dotway/multi-docker-test -f ./client/Dockerfile.dev ./client

script:
  - docker run --env CI=true dotway/multi-docker-test npm test # to force this to exit after tests

after_success:
  - docker build -t dotway/multi-docker-client ./client
  - docker build -t dotway/multi-docker-nginx ./nginx
  - docker build -t dotway/multi-docker-server ./server
  - docker build -t dotway/multi-docker-worker ./worker
  # Login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push dotway/multi-docker-nginx
  - docker push dotway/multi-docker-client
  - docker push dotway/multi-docker-server
  - docker push dotway/multi-docker-worker
  # Take images and push to docker hub

deploy:
  provider: elasticbeanstalk
  region: 'us-west-2'
  app: 'multi-docker'
  env: 'Multidocker-env-1'
  bucket_name: 'elasticbeanstalk-us-west-2-330154092120'
  bucket_path: 'multi-docker'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY