version: '3.8'

services:
  postgres:
    image: 'postgres:latest'
    environment:
      - PG_PASSWORD=postgres_password
  redis:
    image: 'redis:latest'
  nginx:
    restart: always # make sure this baby is always running
    image: "dotway/multi-docker-nginx"
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"
    depends_on:
      - api
      - client
  api:
    image: dotway/multi-docker-server
    hostname: api
    mem_limit: 128m
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PG_USER=$PG_USER
      - PG_HOST=$PG_HOST
      - PG_DATABASE=$PG_DATABASE
      - PG_PASSWORD=$PG_PASSWORD
      - PG_PORT=$PG_PORT
    depends_on: # waits to start api until after redis / postgres started (note might need to specify a more specific command to find out when those services are realllly ready and not just started)
      - redis
      - postgres
  client:
    image: dotway/multi-docker-client
    mem_limit: 128m
    hostname: client
  worker:
    image: dotway/multi-docker-worker
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
    depends_on: 
      - redis
      - postgres