version: '3.8'

services:
  nginx:
    restart: always # make sure this baby is always running
    image: "dotway/multi-docker-nginx"
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"
    depends_on:
      - api
      - client
  api:
    image: dotway/multi-docker-server
    hostname: api
    mem_limit: 128m
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PG_USER=$PG_USER
      - PG_HOST=$PG_HOST
      - PG_DATABASE=$PG_DATABASE
      - PG_PASSWORD=$PG_PASSWORD
      - PG_PORT=$PG_PORT
  client:
    image: dotway/multi-docker-client
    mem_limit: 128m
    hostname: client
  worker:
    image: dotway/multi-docker-worker
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT